### ISSUE TITLE
[bandcamp] breaks with Japanese characters 

### ISSUE THREAD

**Issue by 89z** [89z/mech#47]
https://risatakeda.bandcamp.com/album/the-sorcerers-castle

`github.com/Otiel/BandcampDownloader/issues/213`

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> bandcamp -a https://risatakeda.bandcamp.com/album/the-sorcerers-castle
HEAD https://risatakeda.bandcamp.com/album/the-sorcerers-castle
GET http://bandcamp.com/api/mobile/24/tralbum_details?band_id=1&tralbum_id=575113796&tralbum_type=a
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=252844541&ts=1649791217&t=179ecd03b2e31beefca72d40e76be486f690faeb
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=3579749073&ts=1649791217&t=5f63b507b0588a28cf39d74438bcb50e8eb9a819
71.8%   4.743 MB        9.485 MB/s
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=197080604&ts=1649791217&t=8c2dd1614a2266bbc19582a4027090f12a032df5
94.0%   4.603 MB        9.204 MB/s
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=3473410766&ts=1649791217&t=4fde08b6d54c4280130eca66df3c4a285fd2f06d
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2531226707&ts=1649791217&t=3ef8be6aa47c7eb548543c136ddc95bca8274fd8
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=3399568587&ts=1649791217&t=be4b03fedf505a8b50409554df6acb523888e4c2
80.4%   3.769 MB        7.497 MB/s
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=1782693478&ts=1649791217&t=2c394fb25fbd1525c498f882377bad7c9fe14fd7
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=3438236488&ts=1649791217&t=f9cd4e480c121fb3de48aed0fb0cb584d440c491
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2787278508&ts=1649791217&t=fb77d1ae042b82b8aa6b09190c76e96a1c6fa038
72.2%   3.471 MB        6.904 MB/s
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=436836518&ts=1649791217&t=a0427b3c0e790755e37f4c3cb617f4c8a9d4b9a6
GET https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2437098795&ts=1649791217&t=9250e5bb434b7abc3a8a64225be09cc3a5c9c9d7
99.4%   3.990 MB        7.971 MB/s
~~~

**Comment by 89z** [comment]
https://github.com/Otiel/BandcampDownloader/issues/213

**Comment by 89z** [comment]
@dertuxmalwieder

**Comment by dertuxmalwieder** [comment]
Good to know that there is one more alternative application. Arguably, this does not fix the problem in the original project.

**Comment by 89z** [comment]
If you want to use the other project, you are welcome to. However it seems other project is currently broken. If you have some reason you don't want to use my tool, I am open to feedback.

**Comment by dertuxmalwieder** [comment]
I used `bandcamp-dl` before, but I hated having to reinstall it after every Python upgrade. The *other tool* has two big advantages:

1. I can download multiple albums by just clicking one button, including whole discographies,
2. it has an output template format so I can download albums into `/RandomFolder/Artist/Year/Album`.

**Comment by 89z** [comment]
> I used `bandcamp-dl` before, but I hated having to reinstall it after every Python upgrade.

My tool is not `bandcamp-dl`, is just `bandcamp`, and it doesnt use Python.

> 1. I can download multiple albums by just clicking one button, including whole discographies,

Mine can do that as well.

**Comment by dertuxmalwieder** [comment]
> My tool is not bandcamp-dl, is just bandcamp, and it doesnt use Python.

I know. :-) I tried to explain why *the other tool* ticks some boxes that weren't ticked by any other tool I had tried before. Yours does not seem to be *much* different.

Anyway:

> Mine can do that as well.

It does not have a button. But how can I download multiple albums with just one command?
Templates aren't supported either, as it seems.

**Comment by 89z** [comment]
It seems you are a beggar. Good luck to you.
